import createFetchClient from 'openapi-fetch';
import createClient from 'openapi-react-query';

import type { paths } from './openapi'; // generated by openapi-typescript, run `npm run generate-api` to update

const fetchClient = createFetchClient<paths>({
  baseUrl: process.env.EXPO_PUBLIC_API_URL,
});

export const $api = createClient(fetchClient);
